services:
  # Backend API Service
  - type: web
    name: ml-cogni-backend
    env: python
    plan: starter
    rootDir: backend
    buildCommand: |
      pip install -r Requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        value: sqlite:///cibil_database.db
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Web Service
  - type: web
    name: ml-cogni-frontend
    env: node
    plan: starter
    rootDir: frontend
    buildCommand: |
      npm ci
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: NEXT_PUBLIC_API_URL
        value: https://ml-cogni-backend.onrender.com
      - key: PORT
        value: 3000
    autoDeploy: true
